In [2]:
import numpy as np

常见数学ndim、shape、size、dtype

In [3]:
#np.linspace(0,10,num=5)等间隔分为5个元素
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


numpy不同类型运算时返回能够满足所有元素的新类型

np.diag()生成方阵，可以移动

In [7]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [5]:
np.diag([1, 2, 3],1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

diag（）也可以提取方阵对角元素

In [9]:
a=np.diag([1,2,3],1)
print(np.diag(a))

[0 0 0 0]


vander(x,n)范德蒙矩阵，按列生成，注意n是取不到的，从0到n-1

In [10]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [12]:
np.random.default_rng(42).random((3,2))

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803],
       [0.09417735, 0.97562235]])

np.indices()生成了网格坐标，例如(3,3)，加了一个维度，第一个元素组合(0,0)就是网格(0,0)的坐标，后续一一对应

In [14]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

垂直、水平、分块拼接

In [22]:
A = np.ones((2, 2))
B = np.eye(2, 2)
print(np.vstack((A,B)))
print(np.hstack((A,B)))
print(np.block([A,B]))

[[1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 0. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 0. 1.]]


In [23]:
x = np.arange(5)

In [24]:
x[:,None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [25]:
x[None,:]

array([[0, 1, 2, 3, 4]])

In [30]:
x=np.eye(2,2)
print(x)

[[1. 0.]
 [0. 1.]]


In [32]:
x[...,None]

array([[[1.],
        [0.]],

       [[0.],
        [1.]]])

In [33]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

In [37]:
rows = np.array([[0, 0],
                 [3, 3]])

In [38]:
columns = np.array([[0, 2],
                    [0, 2]])

In [39]:
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

也可以广播或者ix_(指定格式intp)

In [45]:
rows = np.array([0, 3],dtype=np.intp)
columns = np.array([0, 2],dtype=np.intp)

In [46]:
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [47]:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [48]:
x = np.array([[0, 1], [1, 1], [2, 2]])

In [49]:
rowsum = x.sum(1)

In [50]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

使用元组切片

In [51]:
z = np.arange(81).reshape(3, 3, 3, 3)

In [52]:
indices=(1,1,1,slice(0,2))
z[indices]

array([39, 40])

In [54]:
indices=(1,Ellipsis,slice(0,2))
z[indices]

array([[[27, 28],
        [30, 31],
        [33, 34]],

       [[36, 37],
        [39, 40],
        [42, 43]],

       [[45, 46],
        [48, 49],
        [51, 52]]])

单独元组返回不是np.array

In [ ]:
indices=(1,1,1,1)
z[indices]

np.int64(40)

In [56]:
np.nonzero(z)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1,
        1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2,
        0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1,
        1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]),
 array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
        2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
        0, 1, 2, 0, 1, 2, 0, 1

In [59]:
z>0

array([[[[False,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]]])

In [58]:
z[np.nonzero(z)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

# IO

使用genformtxt

# 数据类型

np的数据类型很多，与c++贴合，使用astype()转换
np的int类型不同python，不是无穷的

In [60]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [61]:
np.finfo(np.longdouble) 

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

f64因为是windows下的x86，80位浮点数实际上还是64位

#  副本和视图

基本切片和高级切片就是视图和副本，内部因为类执行规则不同，set和get调用不同

reshape和ravel尽可能返回视图，flatten总是返回副本

可以使用.base属性判断，但是不能判断是不是起始